## This file was auto-generated by CloudCoreo CLI
## This file was automatically generated using the CloudCoreo CLI
##
## This config.rb file exists to create and maintain services not related to compute.
## for example, a VPC might be maintained using:
##
## coreo_aws_vpc_vpc "my-vpc" do
##   action :sustain
##   cidr "12.0.0.0/16"
##   internet_gateway true
## end
##
coreo_aws_rule "cloudtrail-log-file-validating" do
  action :nothing
end

coreo_aws_rule_runner_cloudtrail "advise-cloudtrail" do
  action :run
  rules(${AUDIT_AWS_CLOUDTRAIL_ALERT_LIST}.push("cloudtrail-trail-with-global"))
  regions ${AUDIT_AWS_REGIONS}
end

coreo_aws_rule_runner "advise-cloudtrail-u" do
  action :nothing
end

coreo_aws_rule "cloudtrail-no-global-trails" do
  action :nothing
end
coreo_uni_util_jsrunner "cloudtrail-aggregate" do
  action :nothing
end
coreo_uni_util_variables "cloudtrail-update-planwide-2" do
  action :nothing
end